--------------------------------------------------------
--  File created - Monday-December-11-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LMS_BOOK
--------------------------------------------------------

  CREATE TABLE "HR"."LMS_BOOK" 
   (	"TITLE" VARCHAR2(40 BYTE), 
	"AUTHOR" VARCHAR2(20 BYTE), 
	"ISBN" VARCHAR2(20 BYTE), 
	"TRACKINGID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LMS_CD
--------------------------------------------------------

  CREATE TABLE "HR"."LMS_CD" 
   (	"TITLE" VARCHAR2(40 BYTE), 
	"AUTHOR" VARCHAR2(20 BYTE), 
	"ISBN" VARCHAR2(20 BYTE), 
	"COMPOSER" VARCHAR2(40 BYTE), 
	"TRACKINGID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LMS_VIDEO
--------------------------------------------------------

  CREATE TABLE "HR"."LMS_VIDEO" 
   (	"TITLE" VARCHAR2(40 BYTE), 
	"AUTHOR" VARCHAR2(20 BYTE), 
	"ISBN" VARCHAR2(20 BYTE), 
	"DIRECTOR" VARCHAR2(20 BYTE), 
	"TRACKINGID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.LMS_BOOK
SET DEFINE OFF;
Insert into HR.LMS_BOOK (TITLE,AUTHOR,ISBN,TRACKINGID) values ('a','a','a','a');
Insert into HR.LMS_BOOK (TITLE,AUTHOR,ISBN,TRACKINGID) values ('b','b','b','b');
Insert into HR.LMS_BOOK (TITLE,AUTHOR,ISBN,TRACKINGID) values ('e','e','e','e');
Insert into HR.LMS_BOOK (TITLE,AUTHOR,ISBN,TRACKINGID) values ('c','c','c','c');
Insert into HR.LMS_BOOK (TITLE,AUTHOR,ISBN,TRACKINGID) values ('f','f','f','f');
REM INSERTING into HR.LMS_CD
SET DEFINE OFF;
Insert into HR.LMS_CD (TITLE,AUTHOR,ISBN,COMPOSER,TRACKINGID) values ('b','b','b','b','b');
Insert into HR.LMS_CD (TITLE,AUTHOR,ISBN,COMPOSER,TRACKINGID) values ('c','c','c','c','c');
Insert into HR.LMS_CD (TITLE,AUTHOR,ISBN,COMPOSER,TRACKINGID) values ('a','a','a','a','a');
Insert into HR.LMS_CD (TITLE,AUTHOR,ISBN,COMPOSER,TRACKINGID) values ('e','e','e','e','e');
Insert into HR.LMS_CD (TITLE,AUTHOR,ISBN,COMPOSER,TRACKINGID) values ('d','d','d','d','d');
REM INSERTING into HR.LMS_VIDEO
SET DEFINE OFF;
Insert into HR.LMS_VIDEO (TITLE,AUTHOR,ISBN,DIRECTOR,TRACKINGID) values ('a','a','a','a','a');
Insert into HR.LMS_VIDEO (TITLE,AUTHOR,ISBN,DIRECTOR,TRACKINGID) values ('b','b','b','b','b');
Insert into HR.LMS_VIDEO (TITLE,AUTHOR,ISBN,DIRECTOR,TRACKINGID) values ('c','c','c','c','c');
--------------------------------------------------------
--  DDL for Index LMS_BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."LMS_BOOK_PK" ON "HR"."LMS_BOOK" ("ISBN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LMS_CD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."LMS_CD_PK" ON "HR"."LMS_CD" ("ISBN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LMS_VIDEO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."LMS_VIDEO_PK" ON "HR"."LMS_VIDEO" ("ISBN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger LMS_BOOK_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."LMS_BOOK_TRG" 
BEFORE INSERT ON LMS_BOOK 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."LMS_BOOK_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table LMS_BOOK
--------------------------------------------------------

  ALTER TABLE "HR"."LMS_BOOK" MODIFY ("TRACKINGID" NOT NULL ENABLE);
  ALTER TABLE "HR"."LMS_BOOK" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "HR"."LMS_BOOK" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "HR"."LMS_BOOK" ADD CONSTRAINT "LMS_BOOK_PK" PRIMARY KEY ("ISBN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LMS_CD
--------------------------------------------------------

  ALTER TABLE "HR"."LMS_CD" MODIFY ("TRACKINGID" NOT NULL ENABLE);
  ALTER TABLE "HR"."LMS_CD" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "HR"."LMS_CD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "HR"."LMS_CD" ADD CONSTRAINT "LMS_CD_PK" PRIMARY KEY ("ISBN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LMS_VIDEO
--------------------------------------------------------

  ALTER TABLE "HR"."LMS_VIDEO" MODIFY ("TRACKINGID" NOT NULL ENABLE);
  ALTER TABLE "HR"."LMS_VIDEO" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "HR"."LMS_VIDEO" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "HR"."LMS_VIDEO" ADD CONSTRAINT "LMS_VIDEO_PK" PRIMARY KEY ("ISBN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
